### ISSUE TITLE
Multiple broken links in `packages/cli/README.md`

### ISSUE THREAD

**Issue by akaustav** [coveo/cli#287]
## Describe the bug

The [`packages/cli/README.md`](https://github.com/coveo/cli/blob/master/packages/cli/README.md) file contains at least 8 broken links to code files.
Most of these links are prefixed with - _See code: [src/...](https://github.com/coveo/cli/blob/v1.5.0/src/)_

## To Reproduce

1. Open the main [`README`](https://github.com/coveo/cli#readme) file.

2. Scroll down to this paragraph.

    > In practice, you'll typically want to [`login`](https://github.com/coveo/cli/tree/master/packages/cli#coveo-authlogin) to your Coveo Organization, [`configure`](https://github.com/coveo/cli/tree/master/packages/cli#coveo-configset) the CLI to connect to this organization, and finally create a search page (see [`coveo ui:create:angular NAME`](https://github.com/coveo/cli/tree/master/packages/cli#coveo-uicreateangular-name), [`coveo ui:create:react NAME`](https://github.com/coveo/cli/tree/master/packages/cli#coveo-uicreatereact-name) and [`coveo ui:create:vue NAME`](https://github.com/coveo/cli/tree/master/packages/cli#coveo-uicreatevue-name)).

3. Click on any of the links in that paragraph - which should open the corresponding section within another [`packages/cli/README.md`](https://github.com/coveo/cli/tree/master/packages/cli#readme) file.

4. In this new README file, find lines which begin with - ***See code: src/...*** - for example:
    > _See code: [src/commands/ui/create/angular.ts](https://github.com/coveo/cli/blob/v1.5.0/src/commands/ui/create/angular.ts)_

5. Click on the links on those lines.

6. A **404 - Page Not Found** is shown.

## Expected behavior

The links should open the corresponding code file. **For example:**
> _See code: [packages/cli/src/commands/ui/create/angular.ts](https://github.com/coveo/cli/blob/v1.5.0/packages/cli/src/commands/ui/create/angular.ts)_

## Screenshots

After clicking the broken links, this page is shown:

![image](https://user-images.githubusercontent.com/11030959/123102199-aab8a380-d3e9-11eb-9462-35dae7869507.png)

## Desktop

- OS: Windows
  - OS version: Windows 10 Version 20H2 (OS Build `19042.985`)
- Browser: Google Chrome
  - Browser version: `91.0.4472.77` (Official Build) (64-bit)
- Version of the CLI: `1.5.0`
- Local Node version: `14.17.0`
- Local NPM/Yarn version: `6.14.13`

## Additional context

- Looks like the code files used to be present at folders like this - [src/commands/ui/create/angular.ts](https://github.com/coveo/cli/blob/v1.5.0/src/commands/ui/create/angular.ts), and now have been moved 2 folders deep into [packages/cli/src/commands/ui/create/angular.ts](https://github.com/coveo/cli/blob/v1.5.0/packages/cli/src/commands/ui/create/angular.ts)
- The links to [@oclif/...](https://github.com/oclif) (like [@oclif/plugin-help](https://github.com/oclif/plugin-help/blob/v3.2.2/src/commands/help.ts) and [@oclif/plugin-update](https://github.com/oclif/plugin-update/blob/v1.3.10/src/commands/update.ts)) seem to be working fine.
- These links are broken within the npm repository page for `@coveo/cli` too: https://www.npmjs.com/package/@coveo/cli

**Comment by y-lakhdar** [comment]
Thanks @akaustav for catching this issue.
I have opened the Pull Request (#289) to address it.
